### ISSUE TITLE
Allow for question in url param

### ISSUE THREAD

**Issue by theolundqvist** [felixbade/chatgpt-web-ui#38]
Add possibility to parse question directly from URL params, 

url?q="hi chatgpt!"

This would make it faster to open a new conversation from ex alfred or other launcher.

**Comment by felixbade** [comment]
Good idea! I will use URL hash instead of parameters though, so the question doesn’t get sent to my web server

**Comment by felixbade** [comment]
I wonder how to make this feature discoverable. Maybe the hash could be automatically populated after the first message. This could also make it easier to format it properly.

Then again, that would make it harder to reset the conversation (just a page refresh wouldn’t be enough). Maybe this feature can be made discoverable after there is a setting page (#6).

**Comment by felixbade** [comment]
Maybe adding just a comment about this feature to README would be sufficient before there is a way to add UI elements to the app without cluttering the chat view.

**Comment by felixbade** [comment]
Fixed in bccc402

Example: https://assistant.bloat.app/#q=hello%20there

I'm not sure how to make the links open in the Chrome app / iOS app when that is installed.

**Comment by theolundqvist** [comment]
> Fixed in bccc402
> 
> 
> 
> Example: https://assistant.bloat.app/#q=hello%20there
> 
> 
> 
> I'm not sure how to make the links open in the Chrome app / iOS app when that is installed.

Really cool, well done!
