### ISSUE TITLE
Key error msg doesn't update after typing in the sk-

### ISSUE THREAD

**Issue by smfrue** [felixbade/chatgpt-web-ui#52]
How to reproduce: reloading page without sk-, adding sk and starting to ask questions

**Comment by felixbade** [comment]
It works for me when I follow these steps. Both on Firefox and on Chrome

**Comment by felixbade** [comment]
Ah, now I understand!
1. No API key
2. Send a message
3. Get error
4. Set the correct API key
5. Send another message
6. Get a reply
7. Old error is still there

**Comment by felixbade** [comment]
I need to rethink how the error messages should work altogether. Now they are ”replies” to messages, since that’s what is happening technically. Maybe not the most user-friendly way to think about it though.

**Comment by felixbade** [comment]
Could be worth making a custom text+UI for the most common error states (no API key, incorrect API key, no internet connection)

**Comment by felixbade** [comment]
Fixed in 3889ea6
